# [lock-all/] 🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫🚫
# This workflow will do a clean install of node dependencies, build the source code, run tests, build Storybook, and deploy
# the static Storybook site to GitHub Pages. For more info see: https://github.com/JamesIves/github-pages-deploy-action
# IMPORTANT: You must have an ACCESS_TOKEN secret for the repo. Two steps:
# 1) Create a personal access token with repo access: https://github.com/settings/tokens
# 2) Create the ACCESS_TOKEN secret for your repo: https://github.com/my-username/my-repo-name/settings/secrets
name: Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          # If you're using actions/checkout@v2 you must set persist-credentials to false
          # in most cases for the deployment to work correctly.
          persist-credentials: false
      # https://www.mydatahack.com/how-to-specify-which-node-version-to-use-in-github-actions/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Build 🔧
        run: |
          npm install
          npm run test
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: storybook-static # The folder the action should deploy.
